### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by arkiven4** [VibrasticLab/ehealth-web#1]
- [ ] Add Log File
- [ ] Matlab Support
- [ ] Audiometri API
- [x] Audiometri Chart
- [ ]  Add Verification on Add Device
- [ ]  Doctor login
- [ ]  Doctor ........
- [x]  Add Delete Device
- [x]  Add Response if uploaded file is empty / not exist
- [ ]   Server tensorflow & Matlab Berbeda
